name: cambiodivisa
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2
  

# Add regular de pendencies here.
dependencies:
  http: ^0.13.0
  mysql1: ^0.20.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
